title: Ed Parsons # your name (or website title) here
logo: "/images/edp_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Executive product manager broadly experienced in leading cross-functional teams through the ideation, development, and delivery of technology and data products. 
  <br><br>
  Active user of Python, Google Colab, and Jupyter Notebooks for data exploration, visualization, analysis, and machine learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/edparsonsus/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
